### ISSUE TITLE
How to rerun last debug configuration

### ISSUE THREAD

**Issue by Dimfred** [harrisoncramer/nvim#11]
Hey hey,
thanks for your repo, helps setting up `dap` rn ;)

Found this: https://github.com/harrisoncramer/nvim/blob/main/lua/plugins/dap/init.lua#L78
I think dap has a command for that now: `dap.run_last()`.

Cheers
dimfred

**Comment by harrisoncramer** [comment]
Awesome, thanks! Just pushed up [a commit that adds this to the repository](https://github.com/harrisoncramer/nvim/commit/e5b8ba087e064f2e044271c01abb3e0e47f09481). Appreciate it very much!!!!

If you are curious about debugging in Neovim you may also find my blog post here helpful: https://harrisoncramer.me/debugging-in-neovim/

**Comment by Dimfred** [comment]
Thanks for the blogpost, but finally finished yesterday everything :)
Coming from vimspector have to say DAP is super smooth and fast, and finally I can configure everything as much as I want.
