### ISSUE TITLE
error pausing

### ISSUE THREAD

**Issue by DartMitai** [harrisoncramer/nvim#3]
thank you so much for the article it's great
how can this be fixed?
https://github.com/MitaiDart/dotfiles/blob/master/nvim/lua/plugins/dap.lua
![Снимок экрана от 2022-12-21 17-45-08](https://user-images.githubusercontent.com/104931116/208908637-983c17f0-6584-4a38-a738-c0df65dc3316.png)

**Comment by harrisoncramer** [comment]
Thanks for reading it!

I'm not 100 percent sure, but that looks like it might be an error from the debugger. Looks like you're using Dart, did you follow the installation instructions here: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Dart

I've never used the Dart debugger before, but one thing you might try is setting "info" level logging for DAP:

```lua
    local dap = require("dap")
    dap.set_log_level("TRACE")
 ```

When you do this and try to attach to the debugger, do you see anything helpful in the logs when you run `:DapShowLog` ? This might give you more information to go off.

**Comment by DartMitai** [comment]
yes, there was a whole little investigation, their documentation is outdated. If you follow the link that they give and then a few more, it turns out that now you do not need to install anything else
also, flutter-tools package already have presets
https://github.com/akinsho/flutter-tools.nvim/blob/main/lua/flutter-tools/dap.lua
and the cherry on the cake was your article where you managed to get the ui)) it was an interesting way))

**Comment by harrisoncramer** [comment]
Glad you figured it out!
