### ISSUE TITLE
Comments in `settings.lua` are a little out of order

### ISSUE THREAD

**Issue by cschmatzler** [harrisoncramer/nvim#8]
For example, https://github.com/harrisoncramer/nvim/blob/9789cfc688bbde128736287b78dd04be338ac70c/lua/settings.lua#L17
Comment is for the `unnamedplus` clipboard option, while the setting below sets the regex engine. Then, clipboard settings are another line below, but below a different comment.

**Comment by harrisoncramer** [comment]
Should be fixed now, thanks.

**Comment by cschmatzler** [comment]
No, thank you for having a well-documented setup accessible for people to learn from :)
